version: "3.12"
services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library_db
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  flask-app:
    build:
      context: .
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
